name: Test pull request

on: [push, pull_request]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1
    - name: Set up SQLite
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install sqlite
    - name: Rename sqlite
      run: ren C:\ProgramData\chocolatey\lib\SQLite\tools\sqlite3.dll libsqlite3.a
    - name: Run driver tests
      run: ./gradlew mingwTest --info --debug --stacktrace

env:
  GRADLE_OPTS: "-Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
